### ISSUE TITLE
Java.io.IOEpception: Input/output error while compressing

### ISSUE THREAD

**Issue by darouwan** [xerial/snappy-java#221] opened 2018-09-26 02:03 UTC
Java.io.IOEpception: Input/output error 
at sun.nio.ch.FileDispatcherImpl.write0
at sun.nio.ch.FileDispatcherImpl.write(Fi;eDispatcherImpl.java:60)
at sun.nio.ch.IOUtil.writeFromNatibeBuffer
....
at prg.xerial.snappy.SnappyFramedOutputStream.writeBlock(SnappyFrameOutputStream.java:470)

the version is 1.1.4

**Comment by xerial** [comment] 2020-06-26 07:49
We need more information for reproducing the issue. Let me close this issue since it's outdated.

**Closed by xerial** 2020-06-26 07:49 UTC
