### ISSUE TITLE
Hello, I upgraded to 1.1.9.1 and reported an error when running: glibc_2.23 NOT FOUND

### ISSUE THREAD

**Issue by xizhilanting** [xerial/snappy-java#405] opened 2023-03-20 14:53 UTC
Hello, I upgraded to 1.1.9.1 and reported an error when running: glibc_2.23 NOT FOUND
![image](https://user-images.githubusercontent.com/53000900/226376939-96a7ab53-5a35-41ec-9ae7-31b47184e04e.png)

**Comment by xerial** [comment] 2023-03-20 17:01
It basically means your OS (Linux?) is using a relatively older version of GLIBC. https://www.gnu.org/software/libc/ glibc 2.23 is not so new (released 2 years ago), so I'd recommend using a newer version of the OS.

**Comment by xerial** [comment] 2023-03-21 04:23
Actually, I'm not sure. snappy-java uses dockcross cross compilers https://github.com/dockcross/dockcross There might have been some updates in their docker images and OS versions

**Comment by xizhilanting** [comment] 2023-03-30 02:15
Hello, does snappy-java have lifecycle management and when will 1.1.8.4 end of life?

**Comment by xerial** [comment] 2023-05-16 20:15
Closing as it's a duplicate of #417

**Closed by xerial** 2023-05-16 20:15 UTC
