### ISSUE TITLE
How to use snappy-java with Android?

### ISSUE THREAD

**Issue by spaghetti-** [xerial/snappy-java#174] opened 2017-03-29 18:54 UTC
I've the following string added to my `build.gradle`
```
compile 'org.xerial.snappy:snappy-java:1.1.4-M3'
```
but whenever I try to run my application it it fails with 
```
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library
```

I'm using Android studio with the Android NDK installed.

**Comment by qiuxiaoqiu** [comment] 2017-05-10 06:37
我也想把它用到android上，同样提示找不到本地库，不知道怎么搞才好

**Comment by xerial** [comment] 2017-05-22 15:58
@spaghetti- snappy-1.1.4-M3 should show an error message like:
```
[FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=xxx and os.arch=xxx
```
It seems another version of snappy-java is contained in your classpath.

**Comment by RainSail** [comment] 2017-11-28 01:24
@xerial I use snappy-java-1.1.4 in android and it also fails with
```
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Linux and os.arch=aarch64
   at org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:342)
   at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:176)
   at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:154)
   at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47
```

**Comment by xerial** [comment] 2017-11-30 23:58
It seems aarch64 is wrongly resolved in https://github.com/xerial/snappy-java/blob/master/src/main/java/org/xerial/snappy/OSInfo.java. 

It looks like android should be checked first.

**Comment by xerial** [comment] 2017-12-01 05:56
@RainSail @spaghetti- 
I've made a fix in https://github.com/xerial/snappy-java/commit/a468d08bcacea815f4023f092a4fe5c2c8a3821e. Could you try snappy-java 1.1.7?

If it still doesn't work, it means cross compiler for android is not working as expected.

**Comment by RainSail** [comment] 2017-12-01 07:37
@xerial It still fail with
```
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Linux and os.arch=androidarm
          at org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:342)
          at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:176)
          at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:154)
          at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
```

**Comment by xerial** [comment] 2017-12-01 18:59
Thanks for the report. `os.arch` should be android-arm. So there must be a typo in the OSInfo code.

**Comment by xerial** [comment] 2017-12-01 19:06
@RainSail Could you try this snapshot version?
https://oss.sonatype.org/content/repositories/snapshots/org/xerial/snappy/snappy-java/1.1.7.1-SNAPSHOT/snappy-java-1.1.7.1-SNAPSHOT.jar

**Comment by xerial** [comment] 2017-12-07 19:24
cc: @spaghetti-

**Comment by xerial** [comment] 2017-12-07 19:53
Just released 1.1.7.1 with a potential fix. If you see a different error, let me know.

**Comment by jiechic** [comment] 2018-01-19 02:18
1.1.7.1 also un use for android

**Comment by jiechic** [comment] 2018-01-23 01:28
I compile a snappy library for snappy 
https://github.com/jiechic/Snappy-Android
use source is snappy 1.1.7
ths for snappy-java for java source code

**Comment by xerial** [comment] 2020-06-26 07:47
Added pure-java Snappy implementation since 1.1.7.6. Hopefully it helps android users.

**Closed by xerial** 2020-06-26 07:47 UTC

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment] 2022-07-03 17:32
Hi there,

first of all, thanks for maintaining this snappy-java implementation.
With that being said:
This library does not work on my android 10 device.

First the (full) error log:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.python.companion, PID: 9500
    java.lang.NoSuchMethodError: No virtual method copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at org.xerial.snappy.pure.SnappyRawCompressor.compress(SnappyRawCompressor.java:247)
        at org.xerial.snappy.pure.PureJavaSnappy.rawCompress(PureJavaSnappy.java:97)
        at org.xerial.snappy.Snappy.compress(Snappy.java:151)
        at org.apache.parquet.hadoop.codec.SnappyCompressor.compress(SnappyCompressor.java:78)
        at org.apache.hadoop.io.compress.CompressorStream.compress(CompressorStream.java:74)
        at org.apache.hadoop.io.compress.CompressorStream.finish(CompressorStream.java:85)
        at org.apache.parquet.hadoop.CodecFactory$HeapBytesCompressor.compress(CodecFactory.java:167)
        at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writePageV2(ColumnChunkPageWriteStore.java:246)
        at org.apache.parquet.column.impl.ColumnWriterV2.writePage(ColumnWriterV2.java:84)
        at org.apache.parquet.column.impl.ColumnWriterBase.writePage(ColumnWriterBase.java:387)
        at org.apache.parquet.column.impl.ColumnWriteStoreBase.flush(ColumnWriteStoreBase.java:186)
        at org.apache.parquet.column.impl.ColumnWriteStoreV2.flush(ColumnWriteStoreV2.java:29)
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:185)
        at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:124)
        at org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:319)
        at blue.strategic.parquet.ParquetWriter.close(ParquetWriter.java:76)
        at org.python.exim.Export$writeToParquet$2$1.invokeSuspend(Export.kt:75)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
     Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4d16e98, androidx.compose.runtime.BroadcastFrameClock@e6e96f1, S
```
The top lines are most interesting here.
The problem is that my android device's JDK `sun/misc/Unsafe` class does not have a `method copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V`.
The error is on [this](https://github.com/xerial/snappy-java/blob/8ecc597a0efd2b49daeb007b2b7d5bdb9e0b2564/src/main/java/org/xerial/snappy/pure/SnappyRawCompressor.java#L247) line, where we find function:
```
UNSAFE.copyMemory(inputBase, nextEmitAddress, outputBase, output, literalLength);
```
When checking the java jdk (7 and newer), [this method exists](http://www.docjar.com/html/api/sun/misc/Unsafe.java.html).  
When checking the *android jdk* open source repo, [there is no such function](https://android.googlesource.com/platform/libcore/+/refs/heads/android10-mainline-release/ojluni/src/main/java/sun/misc/Unsafe.java#439).
There is one other `copyMemory` function, with different arguments `(long srcAddr, long dstAddr, long bytes)`.
 > Note that this function exists in both *regular* and *android jdk*.

I don't know why the 5-parameter `copyMemory` function is not present in Android, or why the 3-parameter variant is present in both.
It might have to do with oracle's `sun.misc.Unsafe` to `jdk.internal.misc.Unsafe` move.
According to an [oracle blog](https://blogs.oracle.com/javamagazine/post/the-unsafe-class-unsafe-at-any-speed):
```
The Java 8 Unsafe class, sun.misc.Unsafe, warns us of its very nature immediately, not only in its name, but also by the package in which it lives. 
The sun.misc package is an internal, implementation-specific location, and Java code should never touch it directly.
In Java 9 and later versions, this backstage nature is made even clearer because the functionality of Unsafe moved to a module called jdk.unsupported.
```
It seems like there [will be *android jdk* support for the 5-parameter `copyMemory` in the far future](https://android.googlesource.com/platform/libcore/+/refs/heads/master/ojluni/src/main/java/jdk/internal/misc/).

Until that time is there and all Android phones run a new enough OS, Android people are stuck with the 3-parameter `copyMemory`.

I propose to make the pure java implementation use only 3-parameter `copyMemory`.  
This would involve converting all bytebuffers to direct-allocated bytebuffers.
What do you think @Xerial?
